from django.urls import path

from . import views, views_more

urlpatterns = [
    path("", views.home, name="home"),
    path("nepal/", views.lands, name="lands"),
    path("nepal/<slug:region>/", views.region, name="region"),
    path("nepal/<slug:region>/seasons/<slug:month>/", views.region_month, name="region_month"),
    path("nepal/<slug:region>/styles/<slug:theme>/", views.region_theme, name="region_theme"),
    path("nepal/<slug:region>/experiences/<slug:kind>/", views.region_kind, name="region_kind"),
    path("nepal/<slug:region>/<slug:place>/", views.place, name="place"),
    path("nepal/<slug:region>/<slug:place>/<slug:exp>/", views.experience, name="experience"),
    path("trips/", views.journeys, name="journeys"),
    path("trips/<slug:slug>/", views.journey, name="journey"),
    path("stays/", views.stays, name="stays"),
    path("stays/<slug:slug>/", views.stay, name="stay"),
    path("experiences/", views.experiences, name="experiences"),
    path("experiences/<slug:kind>/", views.experience_kind, name="experience_kind"),
    path("guides/", views.guides, name="guides"),
    path("guides/<slug:slug>/", views.guide, name="guide"),
    path("festivals/", views.festivals, name="festivals"),
    path("festivals/<slug:slug>/", views.festival, name="festival"),
    path("routes/", views.routes, name="routes"),
    path("routes/<slug:slug>/", views.route, name="route"),
    path("styles/", views.themes, name="themes"),
    path("styles/<slug:slug>/", views.theme, name="theme"),
    path("seasons/", views.seasons, name="seasons"),
    path("tools/", views.tools, name="tools"),
    path("tools/season-finder/", views.tool_season, name="tool_season"),
    path("tools/budget/", views.tool_budget, name="tool_budget"),
    path("tools/permits/", views.tool_permits, name="tool_permits"),
    path("plan/", views.plan, name="plan"),
    path("plan/thank-you/", views.plan_thanks, name="plan_thanks"),
    path("about/", views.static_page, {"page": "about"}, name="about"),
    path("stories/", views_more.journal, name="journal"),
    path("stories/topic/<slug:cat>/", views_more.journal, name="journal_cat"),
    path("stories/<slug:slug>/", views_more.post, name="post"),
    path("policies/", views_more.policies, name="policies"),
    path("policies/<slug:slug>/", views_more.policy, name="policy"),
    path("contact/", views_more.contact, name="contact"),
    path("how-we-work/", views_more.how_we_work, name="how_we_work"),
    path("subscribe/", views_more.subscribe, name="subscribe"),
    path("search.json", views_more.search_index, name="search_index"),
    path("faq/", views.faq, name="faq"),
    path("words/", views_more.words, name="words"),
    path("untold/", views_more.untold, name="untold"),
    path("legends/", views_more.legends, name="legends"),
    path("altitude/", views_more.altitude, name="altitude"),
    path("tools/altitude/", views_more.tool_altitude, name="tool_altitude"),
    path("icons/", views_more.icon_sheet, name="icon_sheet"),
    path("privacy/", views.old_policy, {"page": "privacy"}, name="privacy"),
    path("terms/", views.old_policy, {"page": "terms"}, name="terms"),
    path("photo-credits/", views.photo_credits, name="photo_credits"),
    path("sitemap/", views.html_sitemap, name="html_sitemap"),
    path("robots.txt", views.robots, name="robots"),
    path("llms.txt", views.llms, name="llms"),
]
